PS2 Auto Boot
sd2psx/firmware pull request #6
Opened 2023-01-30 06:40 UTC by bbsan2k

This PR will enable autoboot for FMCB in adding a first stage bootloader that is immediately available after startup.
Note: This won't work for usb debug version, as it waits 2 seconds before actually doing the startup.

2023-02-02 05:05 UTC, xyzz requested changes

2023-02-02 05:05 UTC, xyzz commented on src/gui.c
> +
remove these new empty lines

2023-02-02 05:05 UTC, xyzz commented on src/ps2/ps2_memory_card.c
> +        // Skip first 4 Bytes in Buffer, as they are the prefix
this comment doesn't seem to correspond to the code

2023-02-02 05:05 UTC, xyzz commented on src/ps2/ps2_memory_card.c
> +    debug_printf("Write at address %d size %d\n", addr, sz);
remove any debugging output from hot paths e.g. card read/writes

2023-02-02 05:05 UTC, xyzz commented on src/settings.c
> +            settings.ps2_flags &= ~SETTINGS_FLAGS_AUTOBOOT;
```
if (autoboot != settings_get_ps2_autoboot())
  settings.ps2_flags ^= SETTINGS_FLAGS_AUTOBOOT;
```

2023-02-02 05:54 UTC, bbsan2k commented on src/gui.c
> +static void create_exploit_screen(void) {
Done

2023-02-02 05:55 UTC, bbsan2k commented
Issues resolved

2023-02-06 01:43 UTC, xyzz commented
So a couple suggestions regarding the usability:

- I don't think there's a need to support multiple cards under BOOT, it's fine to just have a single one; the autoboot will force channel=1 anyway so it's not like you can easily use the other ones; and more importantly...
- there should be a way to switch off from the BOOT card much easier. I think a button press is reasonable (you could hook into the regular card switch logic rather than tracking button clicks specifically I suppose). For example if I'm playing a game and saving to card id=137, slot=4, and then restart my console, it would be a huge pain to navigate back to it after using autoboot. In the current implementation it basically removes the purpose behind saving last-used card.

2023-02-07 05:22 UTC, xyzz commented
it needs to work on short press also, it's a bit annoying to long press every boot

2023-02-07 05:42 UTC, bbsan2k commented
Here you go!

2023-02-07 07:23 UTC, merged